RELATIONSHIP = (
    ("father", "father"),
    ("mother", "mother"),
    ("son", "son"),
    ("daughter", "daughter"),
    ("husband", "husband"),
    ("wife", "wife"),
    ("brother", "brother"),
    ("sister", "sister"),
    ("grandfather", "grandfather"),
    ("grandmother", "grandmother"),
    ("grandson", "grandson"),
    ("granddaughter", "granddaughter"),
    ("uncle", "uncle"),
    ("aunt", "aunt"),
    ("nephew", "nephew"),
    ("niece", "niece"),
    ("cousin", "cousin"),
    ("friend", "friend"),
    ("friend with family", "friend with family"),
)


BANKS = (
    ("Access Bank", "Access Bank"),
    ("GT Bank", "GT Bank"),
    ("First Bank", "First Bank"),
    ("FCMB", "FCMB"),
    ("Fidelity Bank", "Fidelity Bank"),
    ("UBA", "UBA"),
    ("Zenith Bank", "Zenith Bank"),
    ("Unity Bank", "Unity Bank"),
    ("Stanbic IBTC", "Stanbic IBTC"),
    ("Sterling Bank", "Sterling Bank"),
)
