# Generated by Django 3.2.15 on 2022-09-29 06:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationAccount',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='account name')),
                ('bank_account_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='account number')),
                ('bank_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='account reference id')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='bank name')),
                ('sub_account_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='subaccount id')),
                ('split_type', models.CharField(blank=True, choices=[('percentage', 'percentage'), ('flat', 'flat')], max_length=100, null=True, verbose_name='percentage or flat')),
                ('split_value', models.FloatField(blank=True, max_length=100, null=True, verbose_name='split value')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='balance')),
                ('burial_memory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation_account', to='memorials.burialmemory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_fullname', models.CharField(blank=True, help_text='Your fullname', max_length=200, null=True)),
                ('donor_email', models.CharField(blank=True, help_text='Your email', max_length=200, null=True)),
                ('currency', models.CharField(blank=True, default='NGN', help_text='currency type', max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('trans_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('burial_memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='memorials.burialmemory')),
            ],
        ),
    ]
