# Generated by Django 3.2.15 on 2022-09-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(blank=True, default='NGN', max_length=200, null=True, verbose_name='currency'),
        ),
    ]
