# Generated by Django 3.2.15 on 2022-09-26 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        ('memorials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField(choices=[(1, 'Transaction_Message'), (2, 'Tribute_Message'), (3, 'Gallery_Message'), (4, 'Donation_message')])),
                ('from_admin', models.CharField(blank=True, default='System Notification', max_length=100, null=True)),
                ('donation_by', models.CharField(blank=True, max_length=50, null=True)),
                ('text_preview', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=225, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_from', to=settings.AUTH_USER_MODEL)),
                ('memorial_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_notifications', to='donations.donation')),
                ('memorial_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_notifications', to='memorials.memorygallery')),
                ('memorial_tribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribute_notifications', to='memorials.memorytribute')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_to', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transaction_notifications', to='wallets.wallettransaction')),
            ],
        ),
    ]
